language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - TYPO3_VERSION="^9.5.0"
  - TYPO3_VERSION="^10.4.0"

os: linux

services:
  - mysql

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - breakpoint@schreibersebastian.de

before_install:
  - composer self-update
  - composer --version
  - phpenv config-rm xdebug.ini || return 0

before_script:
  - composer require typo3/minimal=$TYPO3_VERSION
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit --colors -c Build/UnitTests.xml

  - >
    echo;
    echo "Test coverage";
    phpdbg -qrr -d memory_limit=-1 .Build/bin/phpunit -c Build/UnitTests.xml --coverage-clover coverage.xml;
    wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar;
    php php-coveralls.phar --verbose

  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

  - >
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    .Build/bin/phpunit --colors -c Build/FunctionalTests.xml

jobs:
  fast_finish: true
  include:
    - stage: 🚢 to TER
      if: tag IS present
      php: 7.2
      install: skip
      before_script: skip
      script:
        - |
          if [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
            echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n";
            # Install ter client
            composer global require helhum/ter-client
            # Install dependencies
            composer run-script extension-build
            # Upload
            TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
            echo "Uploading release ${TRAVIS_TAG} to TER"
            $HOME/.composer/vendor/bin/ter-client upload typo3_encore . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"
          fi;
